### ISSUE TITLE
"Return" needed twice after current meeting minutes prompt

### ISSUE THREAD

**Issue by bnb** [nodejs/make-node-meeting#27]
Currently it seems there's a bug where `make-node-meeting` needs a second `return` to progress past the entry of meeting minutes for this meeting. 

![image](https://user-images.githubusercontent.com/502396/32018998-bd8ba8a4-b999-11e7-8079-797b6d04f47e.png)

I've been able to reproduce many times, not sure what the issue is exactly.

**Comment by bnb** [comment]
After hitting enter again, it seems this error is returned ABOVE the output markdown: 

```
usr/local/lib/node_modules/make-node-meeting/node_modules/node-meeting-agenda/node-meeting-agenda.js:21
    throw err
    ^

Error: Bad credentials
    at BufferList.afterCreateAuthResponse [as _callback] (/usr/local/lib/node_modules/make-node-meeting/node_modules/ghauth/ghauth.js:40:19)
    at BufferList.end (/usr/local/lib/node_modules/make-node-meeting/node_modules/bl/bl.js:98:10)
    at DuplexWrapper.onend (/usr/local/lib/node_modules/make-node-meeting/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at DuplexWrapper.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at DuplexWrapper.emit (events.js:185:7)
    at /usr/local/lib/node_modules/make-node-meeting/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:934:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by bnb** [comment]
It seems that I've not input any GitHub credentials for this - not sure where/how these are needed. @rvagg can you advise? I assume it has to do with [`node-meeting-agenda`](https://github.com/nodejs/node-meeting-agenda) but I'm not exactly sure how.

**Comment by bnb** [comment]
I was also going to create an issue about [`node-meeting-agenda`](https://github.com/nodejs/node-meeting-agenda) not working, but it seems these two may be the same problem - so I'll leave it here 👍

**Comment by bnb** [comment]
Looks like the in `make-node-meeting` the `node-meeting-agenda` module uses group codes - not sure how/where these are defined, but the [CommComm](https://github.com/nodejs/make-node-meeting/blob/master/examples/cc.sh#L1) one doesn't seem to be working appropriately.

**Comment by Trott** [comment]
@bnb The bad credentials stuff is probably caused by the thing noted at https://github.com/nodejs/node/wiki/Creating-a-CTC-Meeting-Issue: 

> As of this writing (July 2016), the current version of make-node-meeting has a bug such that you will need to run <Path to global node_modules>/make-node-meeting/node_modules/.bin/node-meeting-agenda ctc-agenda to generate a GitHub token once before running make-node-meeting. @rvagg will probably get around to fixing it, but not if you beat him to it and submit a pull request to https://github.com/rvagg/make-node-meeting.
