### ISSUE TITLE
"Local Time" links display incorrectly

### ISSUE THREAD

**Issue by bnb** [nodejs/make-node-meeting#28]
Today I created a meeting with a time of 4pm GMT, but the tool generated the two links to find your "local time" as 8pm. This was noticed and fixed in the issue (https://github.com/nodejs/community-committee/issues/155#issuecomment-339462937), but would be great to understand how we can make this consistent 😁

**Comment by rvagg** [comment]
see #29, someone review that and I'll get it published asap
